In [ ]:

def solve(A_inv, x, k):
  n = len(A_inv)
  k -= 1 # для лучшей индексации
  # ШАГ 1
  l = np.dot(A_inv, x)
  li = l[k] # находим i-ую компоненту вектора l
  if (li == 0): # проверка компоненты на равенство нолю
    return "Матрица не может быть обратимой"
  # ШАГ 2
  l1 = np.copy(l) # получаем вектор l с волной
  l1[k] = -1 # заменяем i-ую компоненту вектора l с волной -1
  # ШАГ 3
  l2 = np.dot(-1/li, l1) # получаем вектор l с шапочкой
  # ШАГ 4
  E = np.eye(n) # создаем единичную матрицу
  Q = np.copy(E)
  #print(l2)
  Q[:,k] = l2.transpose() # создаем матрицу Q
  z = np.eye(n)
  for i in range(n):
    for j in range(n):
      z[i][j] = Q[i][i]*A_inv[i][j]
      if (i != k):
        z[i][j] += Q[i][k]*A_inv[k][j]
  return z

In [ ]:
from scipy.optimize import linprog
import numpy as np
from math import trunc

def branch(c, A, b, x, mod):
  
  res = linprog( c, A, b, bounds = x, method = 'simplex')
  print(res)
  if not res.success:
    return
  else:
    flag = 0
    for i in range(len(res.x)):
      if flag == 1:
        break
      if abs(round(res.x[i]) - res.x[i]) > 10 ** -6:
        flag = 1
        x1 = x[:]
        x1[i] = [0, trunc(res.x[i])]
        branch(c, A, b, x1, mod)
        x2 = x[:]
        x2[i] = [trunc(res.x[i]) + 1, None]
        branch(c, A, b, x2, mod)
    if flag == 0 and abs(round(res.fun) - res.fun) < 10 ** -6:
      print('asdasdasdsad', abs(round(res.fun) - res.fun))
      if mod == 'min':
        if round(res.fun) > ans['global']:
          ans['global'] = round(res.fun)
          ans['x'] = res.x
      else:
        if round(res.fun) < ans['global']:
          ans['global'] = round(res.fun)
          ans['x'] = res.x
        
      


mod = 'max'
    
c = np.array([2,3])



if mod == 'max':
  c *= -1
  ans['global'] *= -1
A = [[3,5], [3,4]]
b = [60,34]
x = [[0, None], [0, 8]]
branch(c, A, b, x, mod)
print(ans['x'])

     con: array([], dtype=float64)
     fun: -25.333333333333332
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([18.,  0.])
  status: 0
 success: True
       x: array([0.66666667, 8.        ])
     con: array([], dtype=float64)
     fun: -24.0
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([20.,  2.])
  status: 0
 success: True
       x: array([0., 8.])
asdasdasdsad 0.0
     con: array([], dtype=float64)
     fun: -25.25
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([18.25,  0.  ])
  status: 0
 success: True
       x: array([1.  , 7.75])
     con: array([], dtype=float64)
     fun: -25.0
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([19.,  0.])
  status: 0
 success: True
       x: array([2., 7.])
asdasdasdsad 0.0
     con: array([], dtype=float64)
     fun: -26.0
 message: "Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective fu

In [ ]:
from scipy.optimize import linprog
import numpy as np
from math import trunc
ans = {'global': -9999999999, 'x': [4]}
def branch(c, A, b, x, mod):
  while True:
    res = linprog( c, A, b, bounds = x, method = 'simplex')
    #print('res.x', res.x)
    flag = 0
    for i in range(len(res.x)):
      if flag == 1:
          break
      if abs(round(res.x[i]) - res.x[i]) > 10 ** -6:
        flag = 1
        x1 = x[:]
        x1[i] = [0, trunc(res.x[i])]
        res1 = linprog( c, A, b, bounds = x1, method = 'simplex')
        #print('res1.x', res1)
        x2 = x[:]
        x2[i] = [trunc(res.x[i]) + 1, None]
        res2 = linprog( c, A, b, bounds = x2, method = 'simplex')
        #print('res2.x', res2)
        if not res1.success and res2.success:
          x = x2[:]
        elif res1.success and not res2.success:
          x = x1[:]
        elif not res1.success and not res2.success:
          return 'Нет корней'
        elif mod == 'min':
          if res1.fun > res2.fun:
            x = x1[:]
          else:
            x = x2[:]
        else:
          if res1.fun < res2.fun:
            x = x1[:]
          else:
            x = x2[:]
    if flag == 0:
      return res.x
mod = 'max'
c = np.array([2, 3])
if mod == 'max':
  c *= -1
  ans['global'] *= -1
A = [[3, 4], [2, 5]]
b = [24, 22]
x = [[0, None], [0, None]]
print(branch(c, A, b, x, mod))

[8. 0.]


In [ ]:
from scipy.optimize import linprog
import numpy as np
c = np.array([7,9])
A = [[-1, 3], [7, 1]]
b = []
x0 = (4, None)
x1 = (0, 2)
res = linprog(c, A, b, bounds = (x0, x1))
print(res)


     con: array([], dtype=float64)
     fun: -6.184410686044725
 message: 'The algorithm terminated successfully and determined that the problem is infeasible.'
     nit: 5
   slack: array([ 7.97580914,  0.81558931, -2.08227325])
  status: 2
 success: False
       x: array([4.22270296, 1.96170772])


/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [ ]:
def get_matrix(av, Jb):
  a = np.eye(len(Jb))
  j = 0
  for i in Jb:
    a[:, j] = av[:, i - 1]
    j += 1
  a = np.linalg.inv(a)
  return a

In [ ]:
def main_simplex(A, c, x, jb):
  iteration = 0
  while True:
    iteration += 1
    if iteration == 1:
      ab = np.array([np.copy(A[:,i-1]) for i in jb]).transpose()
      A_i = np.linalg.inv(ab)
    else:
      ab[:,position_min_tetta] = A[:, jb[position_min_tetta] - 1]
      A_i = solve(A_i, ab[:,position_min_tetta], position_min_tetta + 1)
    cb = np.array([c[i - 1] for i in jb])
    u = np.dot(cb, A_i)
    delta = np.dot(u, A) -c
    j0=0
    if min(delta) >= 0:
      
      return (x, jb)
    while delta[j0]>=0:
      j0 += 1
    z = np.dot(A_i, A[:,j0])
    tetta = [float(x[jb[i] - 1])/float(z[i]) if z[i]> 0 else np.inf for i in range(len(jb))]
    tetta0 = np.min(tetta)
    if tetta0 is np.inf:
      print("целевая функция неограничена на множестве допустимых планов")
    position_min_tetta = np.where(tetta == tetta0)[0][0]
    jb_new = np.copy(jb)
    jb_new[position_min_tetta] = j0 + 1
    x_new = np.copy(x)
    j = 0
    x_new = x_new.astype(np.float64)
    for i in jb:
      x_new[i - 1] = float(x[i - 1]) - tetta0*float(z[j])
      j+=1
    x_new[j0] = tetta0
    x = x_new
    jb = jb_new

In [ ]:
import numpy as np

def begin_simplex(A, b):
  n = len(A[0])
  m = len(b)
  for i in range(m):
    if b[i] < 0:
      b[i] *= -1
      A[i] *= -1
  E = np.eye(m)
  Av = np.empty([m, n + m])
  for i in range(m):
    Av[i] = np.append(A[i], E[i])
  
  x = np.append(np.zeros(n), b)
  
  Jb = np.array([n + i + 1 for i in range(m)])
  c = [0 if i < n else -1 for i in range(n + m)]
  x, jb = main_simplex(Av, c, x, Jb)
  print(x,jb)
  #for i in x[n:]:
    #if abs(i) > 10 ** -6:
    #  return 'Несовместна'
  while True:
    k = -1
    for i in range(len(jb)):
      if (jb[i] > n):
        k = i
    if k == -1:
      return x[:n]
      break
    print(k)
    jnb = []
    for i in range(1, n + 1):
      if not i in jb:
        jnb.append(i)
    print(jnb)
    avb_inv = get_matrix(Av, jb)
    flag = False
    for i in jnb:
      l = np.dot(avb_inv, Av[:,i - 1])
      print(i, l)
      if abs(l[k]) < 10 ** -6:
        jb[k] = i
        flag = True
        break
    print(jb)
    if not flag:
      c = c[:-1]
      jb = jb[:-1]
      A = A[:-1]
      Av = Av[:-1]
      b = b[:-1]

In [ ]:

A = np.array([[2,11], [1, 1], [4, -5], [1, 0]])
b = np.array([38,7,5, -4])
begin_simplex(A, b)

[4.33333333 2.66666667 0.         0.         1.         8.33333333] [5 2 1 6]
3
[]
[5 2 1 6]
0
[]
[5 2 1]
0
[1]


LinAlgError: ignored

In [ ]:
import numpy as np

def read_specific_rows(path, rows=[]):
    with open(path) as f:
        for i, line in enumerate(f):
            if i in rows:
                yield line

def lw_1(matrix, index, vector):
    n = len(matrix)
    l_1 = matrix.dot(vector)
    if l_1[index - 1] == 0:
        return "NO"
    else:
        l_2 = l_1.copy()
        l_2[index - 1] = -1
        l_3 = (-1 / l_1[index - 1]) * l_2
        Q = np.identity(n)
        Q[:, index - 1] = l_3[:]
        #return Q.dot(matrix)
        res = np.identity(n)
        for i in range(n):    
            for j in range(n):
                if (i == index - 1):
                    res[i][j] = Q[i][i] * matrix[i][j]
                else:
                    res[i][j] = Q[i][i] * matrix[i][j] + Q[i][index - 1] * matrix[index - 1][j]
        return res

def get_θ(z, x, J_basis):
    θ = []
    for i in range(len(J_basis)):
        if z[i] > 0:
            θ.append(x[J_basis[i] - 1] / z[i])
        else:
            θ.append(np.inf)
    return θ

def lw_2(A, c, x, J_basis):
    is_first_iteration = True
    A_basis = np.zeros((A.shape[0], len(J_basis)))
    for i, J in enumerate(J_basis):
        A_basis[:, i] = A[:, J-1] 
    A_basis = A_basis.transpose()
    A_inv = np.linalg.inv(A_basis)
    while True:
        if not is_first_iteration:
            A_basis[:, θ_0_index] = A[:, J_basis[θ_0_index] - 1]
            A_inv = lw_1(A_inv, θ_0_index + 1, A_basis[:, θ_0_index])
        else:
            is_first_iteration = False
        c_basis = np.array([c[i - 1] for i in J_basis])
        u = c_basis.dot(A_inv)
        Δ = u.dot(A) - c
        if min(Δ) >= 0:
            return (x, J_basis)
        else:
            J_0 = 0
            for i in Δ:
                if i < 0:
                    break
                else:
                    J_0 += 1
            z = A_inv.dot(A[:, J_0])
            θ = get_θ(z, x, J_basis)
            θ_0 = np.min(θ)
            if θ_0 is np.inf:
                return "UNBOUNDED"
            θ_0_index = 0
            for i in θ:
                if i == θ_0:
                    break
                else:
                    θ_0_index += 1
            new_J_basis = np.copy(J_basis)
            new_J_basis[θ_0_index] = J_0 + 1
            new_x = np.copy(x)
            for i, J in enumerate(J_basis):
                new_x[J - 1] -= θ_0 * z[i]
            new_x[J_0] = θ_0
            x, J_basis = new_x, new_J_basis

#Случай 1
def case_1(new_A, new_A_inv, J_basis, k, n):
    for i in range(1, n + 1): 
        if i not in J_basis:
            if new_A_inv.dot(new_A[:, i - 1])[k] != 0:
                J_basis[k] = i
                return True
    return False

#Случай 2
def case_2(A, new_A, J_basis, k, n):
    i = J_basis[k] - n
    return np.delete(A, i, 0), np.delete(new_A, i, 0), np.delete(J_basis, k, 0)

def lw_3(A, b):
    n, m = A.shape[1], b.shape[0]
    for i, e in enumerate(b):
        if e < 0:
            b[i] *= -1
            A[i] *= -1
    new_A = np.hstack((A.copy(), np.eye(m)))   
    x = np.append(np.zeros(n), b)
    J_basis = np.zeros(m, dtype = int)
    for i in range(m):
        J_basis[i] = n + i + 1
    c = np.zeros(n + m, dtype = int)
    for i in range(n + m):
        if i < n:
            c[i] = 0
        else:
            c[i] = -1
    x, J_basis = lw_2(new_A, c, x, J_basis)
    for i in x[n:]:
        if i != 0:
            return 'INCONSISTENT'
    while True:
    	  J_basis_len = len(J_basis)
        k = None
      
        for i in range(J_basis_len):
            if (J_basis[i] > n):  
                k = i
                break
        if k == None:
            return x[:n]
        else:
            new_A_inv = np.eye(J_basis_len)
            for i, j in enumerate(J_basis):
                new_A_inv[:, i] = new_A[:, i - 1]
            new_A_inv = np.linalg.inv(new_A_inv)
            if not case_1(new_A, new_A_inv, J_basis, k, n):
                A, new_A, J_basis = case_2(A, new_A, J_basis, k, n)

A = np.array([[2,11],[1,1],[4,-5]])
b = np.array([38,7,5])
print("Input:")
print("A:\n", A)
print("b:\n", b)
print("Output:")
print(lw_3(A, b))


IndentationError: ignored

In [ ]:
import scipy.optimize
c = np.array([21,11,0])
A = np.array([[7,4,1]])
b = np.array([13])
x1 = (0, None)
x2 = (0, None)
x3 = (0, None)
e = scipy.optimize.linprog(c,A,b,method='simplex', bounds=(x1,x2,x3))
print(e)

     con: array([], dtype=float64)
     fun: 0.0
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([-1.77635684e-15])
  status: 0
 success: True
       x: array([ 0.,  0., 13.])
